# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFMW2JZEmpxYbOQCGuB4OqtkuE7jQa13
"""

import cv2
import numpy as np
import requests
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model

url = "https://raw.githubusercontent.com/sam2800ml/Inferenciapipeline_proyectoinovacion2/main/Imagen_numeros.jpeg"

# Download image
resp = requests.get(url)

# Función auxiliar para mostrar imágenes grandes y claras en Colab
def mostrar_imagen(titulo, imagen, cmap=None):
    plt.figure(figsize=(8, 8))
    if cmap:
        plt.imshow(imagen, cmap=cmap)
    else:
        # OpenCV usa BGR, Matplotlib usa RGB. Hay que convertir para visualizar bien el color.
        plt.imshow(cv2.cvtColor(imagen, cv2.COLOR_BGR2RGB))
    plt.title(titulo)
    plt.axis('off')
    plt.show()


image_array = np.asarray(bytearray(resp.content), dtype=np.uint8)
img = cv2.imdecode(image_array, cv2.IMREAD_COLOR)

mostrar_imagen("1. Imagen Original", img)

# 2. Escala de grises y Desenfoque
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

mostrar_imagen("2. Escala de Grises + Desenfoque", blurred, cmap='gray')

# 3. Umbralización adaptativa
thresh = cv2.adaptiveThreshold(blurred, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                               cv2.THRESH_BINARY_INV, 51, 10)

mostrar_imagen("3. Umbralización Adaptativa (Trazos blancos)", thresh, cmap='gray')
kernel = np.ones((3,3), np.uint8)
thresh = cv2.dilate(thresh, kernel, iterations=1)

# 5. Extracción de TODOS los contornos (para ver el ruido)
contours, _ = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

img_all_contours = img.copy()
cv2.drawContours(img_all_contours, contours, -1, (0, 255, 0), 2)
mostrar_imagen(f"5. TODOS los contornos detectados: {len(contours)}", img_all_contours)

# 6. Diagnóstico y Filtrado
print("--- Diagnóstico de Áreas ---")
img_filtered = img.copy()
valid_boxes = []

# Guardamos las áreas para verlas
areas_encontradas = []

for c in contours:
    x, y, w, h = cv2.boundingRect(c)
    area = w * h
    areas_encontradas.append(area)

# Ordenamos de mayor a menor para que veas cuáles son los verdaderos números
areas_encontradas.sort(reverse=True)
print(f"Top 10 áreas más grandes: {areas_encontradas[:10]}")

# FILTRADO DINÁMICO
UMBRAL_AREA = 5000

for c in contours:
    x, y, w, h = cv2.boundingRect(c)
    area = w * h

    # También es útil filtrar proporciones extremadamente extrañas (ej. líneas muy finas)
    aspect_ratio = float(w)/h

    if area > UMBRAL_AREA and 0.1 < aspect_ratio < 2.0:
        valid_boxes.append((x, y, w, h))
        cv2.rectangle(img_filtered, (x, y), (x+w, y+h), (255, 0, 0), 5) # Dibujamos un rectángulo azul grueso

valid_boxes.sort(key=lambda b: b[0])
mostrar_imagen(f"6. Resultado Final - Dígitos válidos detectados: {len(valid_boxes)}", img_filtered)

# Lista para guardar los recortes finales
recortes_finales = []

plt.figure(figsize=(10, 4))

for i, box in enumerate(valid_boxes):
    x, y, w, h = box

    # EXTRAER: Cortamos la ROI (Region of Interest) de la imagen 'thresh'
    roi = thresh[y:y+h, x:x+w]

    # ESTANDARIZAR: Por ahora solo haremos un resize simple a 28x28
    recorte_28x28 = cv2.resize(roi, (32, 32), interpolation=cv2.INTER_AREA)

    recortes_finales.append(recorte_28x28)

    # Visualizar cada número separado
    plt.subplot(1, len(valid_boxes), i + 1)
    plt.imshow(recorte_28x28, cmap='gray')
    plt.title(f"Dígito {i+1} Aislado")
    plt.axis('off')

plt.show()

def estandarizar_mnist(roi):
    h, w = roi.shape
    if h > w:
        new_h, new_w = 20, max(1, int(w * (20 / h)))
    else:
        new_w, new_h = 20, max(1, int(h * (20 / w)))

    resized = cv2.resize(roi, (new_w, new_h), interpolation=cv2.INTER_AREA)

    pad_h = (28 - new_h) // 2
    pad_w = (28 - new_w) // 2
    return cv2.copyMakeBorder(resized,
                              pad_h, 28 - new_h - pad_h,
                              pad_w, 28 - new_w - pad_w,
                              cv2.BORDER_CONSTANT, value=0)

# Procesar los recortes que obtuvimos de las bounding boxes
tensores_finales = []
plt.figure(figsize=(10, 4))

for i, box in enumerate(valid_boxes):
    x, y, w, h = box
    roi = thresh[y:y+h, x:x+w] # Usamos 'thresh' porque ya es blanco sobre negro

    # Aplicamos la estandarización estricta
    img_mnist = estandarizar_mnist(roi)
    tensores_finales.append(img_mnist)

    plt.subplot(1, len(valid_boxes), i + 1)
    plt.imshow(img_mnist, cmap='gray')
    plt.title(f"MNIST-Ready {i+1}")
    plt.axis('off')

plt.show()

modelo_cargado = load_model("mi_modelo.h5")

print(f"--- INFERENCIA CORREGIDA (FORZANDO 32x32) ---")


for i, input_image in enumerate(tensores_finales):
    # input_image is already 28x28 — just pad to 32x32
    img_32x32 = np.pad(input_image, [[2, 2], [2, 2]], mode='constant', constant_values=0)
    input_array = img_32x32.reshape(1, 32, 32, 1).astype('float32') / 255.0
    predictions = modelo_cargado.predict(input_array, verbose=0)
    predicted_class = np.argmax(predictions)
    confidence = np.max(predictions) * 100

        # Visualización
    plt.figure(figsize=(2, 2))
    plt.imshow(img_32x32, cmap='gray')
    plt.title(f"Dígito {i+1} -> Pred: {predicted_class}")
    plt.axis('off')
    plt.show()

    print(f'Dígito {i+1} Aislado: Clase {predicted_class} ({confidence:.2f}%)')